### ISSUE TITLE
Review and merge upstream pull requests

### ISSUE THREAD

**Issue by ivy** [go-mail/gomail#1]
The following pull requests are on my list to review and merge:

- [ ] Export NetDialTimeout to public (go-gomail/gomail#100)
- [ ] Added Check For Existing Files And Attachments (go-gomail/gomail#97)
- [ ] Add syntax highlighting to Go example (go-gomail/gomail#92)
- [ ] ~~~fix mail attachment name garbled (go-gomail/gomail#83)~~~ - This one needs more attention to be sure charset encoding is being handled correctly.
- [ ] Break out SMTP Client Reset Method (go-gomail/gomail#79)
- [ ] Accept io.Reader for Attach and Embed (go-gomail/gomail#78)
- [ ] Added Go 1.7 to .travis.yml (go-gomail/gomail#73 go-gomail/gomail#74)
- [ ] Allow timeout in connections, retries to be configurable (go-gomail/gomail#70)
- [ ] ~~~Add support for attaching/embedding files for URLs (go-gomail/gomail#59)~~~ - I believe this kind of behavior is out of the scope of this project. If anyone disagrees we can discuss more.

Any help getting these merged in is much appreciated!

**Comment by pedromorgan** [comment]
Go 1.7 #74 is fixed, its now 1.2 to 1.19

Dropping everything below 1.5 would be handy (no imports)

**Comment by harrisonhjones** [comment]
@ivy @pedromorgan do y'all still need help with this package? It looks like it hasn't seen some love in a little bit of time. I'd like to help if I can.

**Comment by afk11** [comment]
@harrisonhjones Happy to help too. I suggest we discuss this on #68 and discuss yet another fork if needs be.
